openapi: 3.1.0
info:
  title: Mock Orders API
  description: API mock per recuperare lo stato degli ordini clienti
  version: 1.0.0
servers:
  - url: https://your-domain-or-localtunnel/api
paths:
  /orders/{id}:
    get:
      operationId: getOrderById
      summary: Recupera i dettagli di un ordine tramite ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID univoco dell'ordine
          schema:
            type: string
      responses:
        "200":
          description: Dati dell'ordine trovati
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Ordine non trovato
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        customer:
          type: string
        status:
          type: string
        date:
          type: string
        total:
          type: number
        items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              qty:
                type: integer
              price:
                type: number
